### ISSUE TITLE
SHA2 256 upgrade

### ISSUE THREAD

**Issue by Tim-W** [Tribler/kotlin-ipv8#22]
If I understand correctly, the service ID generated in TrackerCommunity class uses a sha1 hash of a private key. Should this be upgraded to a more secure hashing algorithm (sha2?)
```
    override val serviceId: String = sha1(defaultCryptoProvider.generateKey().keyToBin()).toHex()
```

**Comment by MattSkala** [comment]
Note that `TrackerCommunity` is not a real community, it only extends the `Community` class to simplify the implementation of the bootstrap server. I believe the service ID in `TrackerCommunity` is not used for anything and not included in any messages. It is there only because it is required by the `Overlay` interface. `TrackerCommunity` overrides `onPacket` method to be able to handle introduction requests coming from any community and it copies the service ID of the introduction request to the introduction response packet.

Regarding the service ID of other communities, you can use any 20-byte hexadecimal string, as long as it is unique and does not clash with any existing communities.

SHA1 is used also for generating a peer ID (`Peer.mid`) from the public key. This is the place where I would be more concerned with its security. AFAIK, peer ID is not used anywhere in the protocol, usually public keys are used directly. The hash is only used to display peer identity in the UI. So you should also be able to use any other hash function if you need it in your application.

The security of the hash function also matters when generating the hashes of TrustChain blocks (`TrustChainBlock.calculateHash`), where SHA256 is used already.
